### ISSUE TITLE
Share data/service between admin and agent

### ISSUE THREAD

**Issue by HenryZerocool** [HenryZerocool/Seneca-iap#11]

**Comment by suleiManiac** [comment]
Hello, I would like to at least try to work on this but there's no description. What's the issue exactly please?

**Comment by HenryZerocool** [comment]
Hi there,
We are a group of internships working for Seneca. I made this repo public cuz there is no Seneca property in it right now. And we are using gitHub as a task management tool for now.
If you are still interested in the issue, I will explain more.
Thanks

**Comment by suleiManiac** [comment]
@HenryZerocool , I am still interested. But let me post a caveat. I am a newbie developer so I might not be able to fix the issue. I'm willing to try though.
