### ISSUE TITLE
form validation

### ISSUE THREAD

**Issue by HenryZerocool** [HenryZerocool/Seneca-iap#13]

**Comment by suleiManiac** [comment]
@HenryZerocool will like to try to fix this too

**Comment by HenryZerocool** [comment]
Let's start with this issue first. Please follow these steps to start developing:
- clone the project
- in your console type "npm install", then switch branch "git checkout form_validation"
- run develop server "ng serve"
The form needs to be validate is on this link "http://localhost:4200/admin/content/newsfeed/new"
The idea is the form need to be validated before "Save"
The component is "app/iap/iap-admin/iap-content/admin-newsfeeds/admin-newsfeed/admin-newsfeed.component.html"
Good luck!

**Comment by suleiManiac** [comment]
Thanks a bunch. will get right on it

**Comment by HenryZerocool** [comment]
Hi there, I received the pull request. Its busy for us this week so I will take a look at it later.
Thanks a lot

**Comment by suleiManiac** [comment]
No problems. Thanks for allowing me at least try to help. All the best
